import time
import random
from playsound import playsound
import webbrowser

def menu():
    mn=input("Добрый день! \nВас приветствует игра >-ADLER HULY-< \n\nНачать Игру - |1| \nАвторы - |2| \nВыйти из игры - |3| \nВведите действие: ")
    if mn == "1" or mn == "|1|":
        print("\n"*10)
        igra()
    if mn =="2" or mn == "|2|":
        print("\n"*10)
        time.sleep(1)
        print("\n...Ща думаюююююююююююю...")
        time.sleep(2)
        print("...Еще секундочку...")
        time.sleep(2)
        print("... ОООшиБББкаа ...")
        time.sleep(1)
        print("...гоонеееееееееепппппп433errrrrrooor...")
        time.sleep(2)
        print("\nРазработчик - Avedy")
        bk=input("Нажмите любую кнопку, чтобы вернуться в меню \nВведите действие: ")
        if bk:
            print("\n"*10)
            menu()
    if mn == "3" or mn == "|3|":
        print("\n")
        print("Выход из игры..".center(150))
        time.sleep(1.5)
        print("\n"*10)
        print("Ждём вас снова :)".center(150))
        print("\n"*3)


def igra():
    time.sleep(2.5)
    print("\n")
    print("-----Avedy-----".center(150))
    #НЕ ЗАБЫТЬ ЗАГРУЗИТЬ МОДУЛЬ ПРОИГРЫВАНИЯ PLAYSOUND
    time.sleep(2.5)
    print("--представляет--".center(150))
    time.sleep(2.5)
    print("---ADLER HULY---".center(150))
    time.sleep(2)
    print("\n"*3)
    print("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n"*22)
    time.sleep(0.3)
    print("\n"*22)
    time.sleep(2)
    print("Среда".center(150))
    time.sleep(2)
    print("Время 07:00".center(150))
    time.sleep(2)
    print("Звонит будильник, пора вставать!".center(150))
    time.sleep(1)
    print("\n")
    budilnik=input("Встать с кровати и пойти в душ - |1| \nВыключить будильник и продолжить спать - |2| \n(Просто так Enter не нажимать!) \nВведите действие: ")
    if budilnik == "1" or budilnik == "|1|":
        vstal()
    if budilnik == "2" or budilnik == "|2|":
        prospal()


def vstal():
    print("\n"*10)
    time.sleep(2)
    print("Ты искупался, поел, почистил зубы.".center(150))
    print("\n"*3)
    time.sleep (2.5)
    print("\n"*10)
    time.sleep(2)
    print("Время 08:00".center(150))
    time.sleep(1.5)
    vihod()


def prospal():
    print("\n"*10)
    print("Время 08:30".center(150))
    time.sleep(2)
    print("Ты быстро искупался, быстро поел, быстро почистил зубы.".center(150))
    print("\n"*3)
    time.sleep (3)
    print("\n"*10)
    time.sleep(1.5)
    print("Время 08:40".center(150))
    time.sleep(2)
    vihod()


def halyava():
    print("Ты выходишь на улицу с Максончиком, Лёней и Олегом Юрьевичем".center(150))
    time.sleep(3)
    print("Вы решаете на какой машине ехать в Лицей".center(150))
    time.sleep(2)
    print("\n")
    car = input("Поехать на Макса машине с аргументом, что если он не поедет, то Олег Юрьевич его отчислит :) - |1| \nПоехать на своей машине с кайфом, чтобы дать на прямой 140 км/ч - |2| \n(Просто так Enter не нажимать!) \nВведите действие: ")
    if car == "1" or car == "|1|":
        print("\n"*10)
        time.sleep(2)
        print("Вы поехали на приусе (зато свой 100-ый бензин тратить не надо)".center(150))
        print("\n"*3)
        time.sleep(4)
        print("\n"*10)
        time.sleep(2)
        licey()
    if car == "2" or car == "|2|":
        print("\n"*10)
        print("Вы поехали с кайфом на гольфе в Лицей".center(150))
        print("\n"*3)
        time.sleep(3)
        print("\n"*10)
        time.sleep(2)
        licey()


def licey():
    print("Время 12:25".center(150))
    time.sleep(2)
    print("Вы все вместе заходите в Лицей и идёте в столовую".center(150))
    time.sleep(2)
    print("В столовой каждый из вас покупает пельмени, потому что за 100 рублей в этом мире ничего лучше нету".center(150))
    print("\n"*3)
    time.sleep(5)
    print("\n"*10)
    time.sleep(2)
    print("Вы сидите кушаете".center(150))
    time.sleep(2)
    print("\n"*10)
    time.sleep(2)
    print("Время 12:42".center(150))
    time.sleep(2)
    print("Вы все с таким кайфоооооооом наелись, что идти трудно".center(150))
    time.sleep(2)
    print("Вы уходите из Лицея и возвращаетесь обратно в арену :(".center(150))
    time.sleep(5)
    print("\n"*10)
    time.sleep(2)
    third_para()


def secret():
    parol=input("Введите пароль: ")
    if parol == "huly":
        print("\n"*10)
        time.sleep(1.5)
        print("Пароль верный!".center(150))
        print("\n"*3)
        time.sleep(1.5)
        webbrowser.open('https://youtu.be/Rf5puZhkqKA', new=1)
        time.sleep(2)
        print("\n"*10)
        print("\033[38m")
        time.sleep(1.5)
        return menu()
    if parol != "huly":
        print("\n"*10)
        time.sleep(1.5)
        print("Пароль неверный!".center(150))
        print("\n"*3)
        time.sleep(1.5)
        print("\n"*10)
        time.sleep(1.5)
        return secret()


def vihod():
    print("Тебе нужно спуститься с 3 этажа на 1 этаж".center(150))
    time.sleep(2)
    print("\n")
    spusk=input("Спуститься по лестнице - |1| \nСпуститься на лифте - |2| \n(Просто так Enter не нажимать!) \nВведите действие: ")
    vnizy = "Ты спустился во двор".center(150)
    if spusk == "1" or spusk == "|1|":
        print("\n"*10)
        time.sleep(2)
        print(vnizy)
    if spusk == "2" or spusk == "|2|":
        print("\n"*10)
        print("У тебя частный дом и в нём нету лифта -_-".center(150))
        print("\n"*3)
        time.sleep(2)
        print("\n"*10)
        time.sleep(1.5)
        print(vnizy)
    print("\n"*3)
    time.sleep(2)
    print("\n"*10)
    time.sleep(1.5)
    print("Ты садишься в свой Volkswagen Golf GTI mk5 2008 года и заводишь его".center(150))
    time.sleep(3)
    print("Пока ты греешь машину, ты вспоминаешь, что сегодня ты снова учишься в еб@@@ арене".center((150)))
    time.sleep(3)
    print("Но первой парой Олег Юрьевич, и тебя это успокаивает".center(150))
    time.sleep(3)
    print("Ты врубаешь песню MACAN'а и выезжаешь со двора".center(150))
    print("\n")
    time.sleep(4)
    print("\n"*10)
    time.sleep(1.5)
    print("Ты подъезжаешь к арене".center(150))
    time.sleep(2)
    print("Ты видишь машину Макса, обгоняешь его малолитражку приус и паркуешься".center(150))
    time.sleep(4)
    print("Ты выходишь из машины и видишь, что Максончик-то приехал с Олегом Юрьевичем, вы приветствуетесь и идёте вместе на пары".center(150))
    print("\n"*2)
    time.sleep(5.5)
    print("\n"*10)
    time.sleep(2)
    print("На паре Олег Юрьевич говорит, что у тебя лучшая проектная работа".center(150))
    time.sleep(4)
    print("Ты очень счастлив, что получаешь автомат на зачёте, но после ты вспоминаешь что".center(150))
    time.sleep(4)
    print("второй парой алгоритмы :(".center(150))
    print("\n"*2)
    time.sleep(5)
    print("\n"*10)
    time.sleep(2)
    print("Ты отсижываешь хз как вторую пару".center(150))
    time.sleep(3)
    print("Нужно пойти похавать".center(150))
    time.sleep(1)
    print("\n")
    pohavat = input("Поехать как волк в Лицей - |1| \nПойти в аренскую столовую - |2| \n(Просто так Enter не нажимать!) \nВведите действие: ")
    if pohavat == "1" or pohavat == "|1|":
        print("\n"*10)
        time.sleep(2)
        halyava()
    if pohavat == "2" or pohavat == "|2|":
        print("\n"*10)
        print("Ты поел на 960.768 рублей пюре с гонепом".center(150))
        time.sleep(2)
        print("Ты обиженный идешь на английский :(".center(150))
        print("\n"*3)
        time.sleep(2)
        print("\n"*10)
        time.sleep(2)
        print("Ты пришел на английский, увидел лицо Маргариты Сергеевны, и твоё хорошее настроение вернулось обратно :)".center(150))
        print("\n" * 3)
        time.sleep(4)
        print("\n" * 10)
        time.sleep(2)
        third_para()


def third_para():
    print("Время 13:15".center(150))
    time.sleep(2)
    print("Урок инглиша начался".center(150))
    print("\n" * 3)
    time.sleep(2)
    print("\n" * 10)
    time.sleep(2)
    print("Margarita: Do you like lessons of Oleg Yurievich?".center(150))
    print("\n")
    english = input("Yes, I like it - |1| \nNo, I don't like it - |2| \n(Просто так Enter не нажимать!) \nВведите действие: ")
    if english == "1" or english == "|1|":
        print("\n" * 10)
        time.sleep(1)
        print("Margarita: OK, good answer, sit down, your mark is 5".center(150))
        print("\n"*3)
        time.sleep(3)
    if english == "2" or english == "|2|":
        print("\n" * 10)
        time.sleep(1)
        print("Margarita: OK, you will cut on your next lesson by Oleg Yurievich, sit down, your mark is 1".center(150))
        print("\n"*3)
        time.sleep(3)
    print("\n"*10)
    time.sleep(1.5)
    print("3 пара закончилась".center(150))
    print("\n"*3)
    time.sleep(2)
    print("\n"*10)
    time.sleep(1.5)
    print("Осталась последняя пара - снова алгоритмы".center(150))
    print("\n"*3)
    time.sleep(3)
    print("\n"*10)
    time.sleep(1.5)
    print("Время 14:53".center(150))
    time.sleep(1.5)
    print("Ты очень экстраординарным способом хочешь решить, идти на алгоритмы, или нет".center(150))
    print("\n"*3)
    time.sleep(4)
    print("\n"*10)
    time.sleep(2)
    print("Ты достаешь телефон и пишешь в нем программу, выдающую рандомный выбор между 'идти' или 'не идти'".center(150))
    time.sleep(3)
    print("\n")
    danet="Идти", "Не идти"
    input("Нажмите любую кнопку \n(Просто так Enter не нажимать!) \nВведите действие: ")
    time.sleep(1.5)
    rndm=random.choice(danet)
    print(rndm.center(150))
    time.sleep(3)
    if rndm == "Идти":
        print("\n"*10)
        time.sleep(2)
        print("Эх, всё равно домой поеду, по закону Гроша 4 пара придумана для того, чтобы на неё не ходить!".center(150))
        print("\n"*3)
        time.sleep(5)
    if rndm == "Не идти":
        print("\n"*10)
        time.sleep(2)
        print("Ох, щас с таким кайфом уеду домой, лесгоуу".center(150))
        print("\n"*3)
        time.sleep(5)
    print("\n"*10)
    time.sleep(3)
    print("Время 16:01".center(150))
    print("\n"*3)
    time.sleep(2)
    print("\n"*10)
    time.sleep(2)
    print("Ты спускаешься на парковку арены, садишься в машину".center(150))
    print("\n"*3)
    time.sleep(3)
    print("\n"*10)
    time.sleep(2)
    print("Ты едешь домой под кайфовую музычку".center(150))
    print("\n"*3)
    time.sleep(3)
    print("\n"*10)
    time.sleep(2)
    print("Конец игры :)".center(150))
    print("\n"*3)
    playsound('gosling.mp3')
    print("\n"*10)
    time.sleep(2)
    print("\033[31mХотите ли вы увидеть секреточку?".center(150))
    print("\n"*3)
    time.sleep(0.5)
    scrt=input("\033[31mДа - |1| \nНет - |2| \nВведите действие: ")
    if scrt == "1" or scrt == "|1|":
        print("\n"*10)
        time.sleep(2)
        secret()
    if scrt == "2" or scrt == "|2|":
        print("\n"*10)
        time.sleep(2)
        return menu()


menu()